<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <?php
        if(isset($error)){
            echo $error;
        }
    ?>
    <div class="card" style="width: 18rem; margin: auto; margin-top:10%">
        <div class="card-body">
            <form action='index.php?crearArti' method='POST' enctype="multipart/form-data">
                <div class="form-group">
                    <label for="nombre">Nombre</label>
                    <input type="text" class="form-control" id="nombre" aria-describedby="nombre" placeholder="Nombre del artículo" name='nombre'>
                </div>
                <div class="form-group">
                    <label for="desc">Descripción</label>
                    <input type="text" class="form-control" id="desc" aria-describedby="desc" placeholder="Descripción del artículo" name='desc'>
                </div>
                <div class="form-group">
                    <label for="imagen">Imagen</label>
                    <input type="file" class="form-control" id="imagen" aria-describedby="imagen" placeholder="Imagen del artículo" name='imagen' style='padding:1%;'>
                </div>
                <div class="form-group">
                    <label for="precio">Precio</label>
                    <input type="number" class="form-control" id="precio" aria-describedby="precio" placeholder="Precio del artículo" name='precio'>
                </div>
                <div class="form-group">
                    <label for="cantidad">Cantidad</label>
                    <input type="number" class="form-control" id="cantidad" aria-describedby="cantidad" placeholder="Cantidad del artículo" name='cantidad'>
                </div>
                <button type="submit" class="btn btn-primary" name='enviar'>Submit</button>
            </form>
        </div>
    </div>
</body>
</html>