<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Preguntas de Mierda</title>
</head>
<body>
    <a href="index.php">Salir</a> <br>
    <?php
        
        if($formulario){
            ?>
            <h2>Login</h2>
            <form action="index.php?login" method="post">
                <input type="text" name="user" placeholder="Usuario"/>
                <input type="password" name="password" placeholder="Contraseña"/>
                <input type="submit" name="logeo" value="Entrar"/>
            </form>
            <?php
        }else{
            ?>
            <h2>Registro</h2>
            <form action="index.php?register" method="post">
                <input type="text" name="nombre" placeholder="Nombre"/>
                <input type="text" name="apellido" placeholder="Apellido"/>
                <input type="mail" name="correo" placeholder="Correo"/>
                <br> <br>
                <input type="text" name="user" placeholder="Usuario"/>
                <input type="password" name="password" placeholder="Contraseña"/>
                <input type="password" name="password2" placeholder="Repite la contraseña"/>
                <br><br>
                <input type="submit" name="register" value="Registrarse">
            </form>
            <?php
        }
    ?>
</body>
</html>