<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda</title>
    <link rel="stylesheet" href="views/css/maincss.css">
</head>
<body>
    <?php
        if($_SESSION['user']->getId()!=0){
            if($_SESSION['user']->getRol()==1){
                echo '<a href="index.php?crearArti">Añadir artículo</a> ';
                echo '<a href="index.php?modUsers">Modificar usuarios</a> ';
            }
            echo '<a href="index.php?logout" >Salir</a> <br>';
            echo '<a href="index.php?verCarrito">Ver Carrito ('.$artsCount.')</a> ';
            echo '<a href="index.php?verPedidos">Ver pedidos realizados</a> <br>';
            echo 'Hola '.$_SESSION['user']->getName();
        }
        else{
            echo '
                <p>
                    <a href="index.php?login">Login</a>
                    <a href="index.php?register">Register</a>
                </p>
                ';
        }
        echo '<br>';
        
    ?>
    <div>
        <div class="prueba">

        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script type="text/javascript">
        var start=0;
        var limit=4;
        var reachedMax=false;
        
        $(window).scroll(function (){
            if($(window).scrollTop()==$(document).height()- $(window).height()){
                getData();
            }
        })

        $(document).ready(function () {
            getData();
            console.log(start);
            
        });

        function getData(){
            if(reachedMax)
                return;
                
            $.ajax({
                url: 'index.php',
                method: 'POST',
                dataType: 'text',
                data: {
                    getData:1,
                    start: start
                    <?php
                        if($_SESSION['user']->getId()!=0){
                            echo ", \n idus: ".$_SESSION['user']->getId();
                        }
                    ?>,
                    
                }, 
                 success: function(response){
                    if(response== "reachedMax"){
                        reachedMax=true;
                    }else{
                        start += limit;
                        $(".prueba").append(response);
                        
                        
                    }
                 }
            })
        }
    </script>
</body>
</html>